# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cdc_operations.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CdcOperationsDialog(object):
    def setupUi(self, CdcOperationsDialog):
        CdcOperationsDialog.setObjectName("CdcOperationsDialog")
        CdcOperationsDialog.resize(441, 323)
        self.buttonBox = QtWidgets.QDialogButtonBox(CdcOperationsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(140, 280, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.collateralBox = QtWidgets.QLineEdit(CdcOperationsDialog)
        self.collateralBox.setGeometry(QtCore.QRect(160, 80, 133, 20))
        self.collateralBox.setReadOnly(True)
        self.collateralBox.setObjectName("collateralBox")
        self.label_2 = QtWidgets.QLabel(CdcOperationsDialog)
        self.label_2.setGeometry(QtCore.QRect(73, 80, 81, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.cdcIdBox = QtWidgets.QLineEdit(CdcOperationsDialog)
        self.cdcIdBox.setEnabled(True)
        self.cdcIdBox.setGeometry(QtCore.QRect(160, 50, 133, 20))
        self.cdcIdBox.setReadOnly(True)
        self.cdcIdBox.setObjectName("cdcIdBox")
        self.label_3 = QtWidgets.QLabel(CdcOperationsDialog)
        self.label_3.setGeometry(QtCore.QRect(93, 50, 61, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(CdcOperationsDialog)
        self.label_4.setGeometry(QtCore.QRect(300, 80, 61, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(CdcOperationsDialog)
        self.label_5.setGeometry(QtCore.QRect(300, 110, 61, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(CdcOperationsDialog)
        self.label_6.setGeometry(QtCore.QRect(93, 110, 61, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.generatedBox = QtWidgets.QLineEdit(CdcOperationsDialog)
        self.generatedBox.setGeometry(QtCore.QRect(160, 110, 133, 20))
        self.generatedBox.setReadOnly(True)
        self.generatedBox.setObjectName("generatedBox")
        self.label_7 = QtWidgets.QLabel(CdcOperationsDialog)
        self.label_7.setGeometry(QtCore.QRect(63, 140, 91, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.stabilityFeeBox = QtWidgets.QLineEdit(CdcOperationsDialog)
        self.stabilityFeeBox.setGeometry(QtCore.QRect(160, 140, 133, 20))
        self.stabilityFeeBox.setReadOnly(True)
        self.stabilityFeeBox.setObjectName("stabilityFeeBox")
        self.label_8 = QtWidgets.QLabel(CdcOperationsDialog)
        self.label_8.setGeometry(QtCore.QRect(300, 140, 61, 20))
        self.label_8.setObjectName("label_8")
        self.stateBox = QtWidgets.QLineEdit(CdcOperationsDialog)
        self.stateBox.setGeometry(QtCore.QRect(160, 170, 133, 20))
        self.stateBox.setReadOnly(True)
        self.stateBox.setObjectName("stateBox")
        self.label_9 = QtWidgets.QLabel(CdcOperationsDialog)
        self.label_9.setGeometry(QtCore.QRect(63, 170, 91, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.cdcActionBox = QtWidgets.QComboBox(CdcOperationsDialog)
        self.cdcActionBox.setGeometry(QtCore.QRect(80, 200, 71, 22))
        self.cdcActionBox.setObjectName("cdcActionBox")
        self.cdcActionBox.addItem("")
        self.cdcActionBox.addItem("")
        self.cdcActionBox.addItem("")
        self.cdcActionBox.addItem("")
        self.cdcActionArg = QtWidgets.QLineEdit(CdcOperationsDialog)
        self.cdcActionArg.setEnabled(True)
        self.cdcActionArg.setGeometry(QtCore.QRect(160, 200, 133, 20))
        self.cdcActionArg.setReadOnly(False)
        self.cdcActionArg.setObjectName("cdcActionArg")
        self.label_10 = QtWidgets.QLabel(CdcOperationsDialog)
        self.label_10.setGeometry(QtCore.QRect(63, 230, 91, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.ratioBox = QtWidgets.QLineEdit(CdcOperationsDialog)
        self.ratioBox.setGeometry(QtCore.QRect(160, 230, 133, 20))
        self.ratioBox.setReadOnly(True)
        self.ratioBox.setObjectName("ratioBox")

        self.retranslateUi(CdcOperationsDialog)
        self.buttonBox.accepted.connect(CdcOperationsDialog.accept)
        self.buttonBox.rejected.connect(CdcOperationsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CdcOperationsDialog)

    def retranslateUi(self, CdcOperationsDialog):
        _translate = QtCore.QCoreApplication.translate
        CdcOperationsDialog.setWindowTitle(_translate("CdcOperationsDialog", "CDC Operations"))
        self.label_2.setText(_translate("CdcOperationsDialog", "Collateral:"))
        self.label_3.setText(_translate("CdcOperationsDialog", "CDC ID:"))
        self.label_4.setText(_translate("CdcOperationsDialog", "BTC"))
        self.label_5.setText(_translate("CdcOperationsDialog", "USD"))
        self.label_6.setText(_translate("CdcOperationsDialog", "Generated:"))
        self.label_7.setText(_translate("CdcOperationsDialog", "Stability Fee:"))
        self.label_8.setText(_translate("CdcOperationsDialog", "USD"))
        self.label_9.setText(_translate("CdcOperationsDialog", "State:"))
        self.cdcActionBox.setItemText(0, _translate("CdcOperationsDialog", "Payback"))
        self.cdcActionBox.setItemText(1, _translate("CdcOperationsDialog", "Withdraw"))
        self.cdcActionBox.setItemText(2, _translate("CdcOperationsDialog", "Close"))
        self.cdcActionBox.setItemText(3, _translate("CdcOperationsDialog", "Liquidate"))
        self.label_10.setText(_translate("CdcOperationsDialog", "Ratio:"))
